spring:
  boot:
    admin:
      url: http://localhost:8090
      client:
        enabled: true
  application:
    name: ServiceDemo
server:
  port: 8044
logging:
  level:
   root: info
#eureka:
#  instance:
#  client:
#    serviceUrl:
#      defaultZone: http://admin:admin@localhost:8761/eureka/
